[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
authors = ["Emma <queer_emma@protonmail.com>"]

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
thiserror = "1.0"
regex = "1.7"
lazy_static = "1.4"
