[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
authors = ["Emma <queer_emma@protonmail.com>"]

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
thiserror = "1.0"
pretty_env_logger = "0.4"
log = "0.4"
